[versions]
crate = "4.0.0-RC.3"
commandapi = "10.1.1"
flyway = "11.10.3"

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.2"
paper-api = "io.papermc.paper:paper-api:1.21.5-R0.1-SNAPSHOT"
morepaperlib = "space.arim.morepaperlib:morepaperlib:0.4.4"

# API dependencies
crate-api = { module = "io.github.milkdrinkers:crate-api", version.ref = "crate" }
crate-yaml = { module = "io.github.milkdrinkers:crate-yaml", version.ref = "crate" }
colorparser = "io.github.milkdrinkers:colorparser:3.0.1"
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade", version.ref = "commandapi" }
triumph-gui = "dev.triumphteam:triumph-gui:3.1.12"

# Plugin dependencies
vault = "com.github.MilkBowl:VaultAPI:1.7.1"
placeholderapi = "me.clip:placeholderapi:2.11.6"
towny = "com.palmergames.bukkit.towny:towny:0.101.2.0"
dynmap = "us.dynmap:DynmapCoreAPI:3.7-beta-6"
worldguardbukkit = "com.sk89q.worldguard:worldguard-bukkit:7.0.14"

# Database dependencies
hikaricp = "com.zaxxer:HikariCP:7.0.2"
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
jooq = "org.jooq:jooq:3.20.5"

# JDBC drivers
h2 = "com.h2database:h2:2.3.232"
sqlite = "org.xerial:sqlite-jdbc:3.49.1.0"
mysql = "com.mysql:mysql-connector-j:9.4.0"
mariadb = "org.mariadb.jdbc:mariadb-java-client:3.5.2"

# Testing
junit-bom = "org.junit:junit-bom:5.13.4"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j = "org.slf4j:slf4j-simple:2.1.0-alpha1"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.20.6"
testcontainers-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }

[bundles]
flyway = ["flyway-core", "flyway-mysql"]
jdbcdrivers = ["h2", "sqlite", "mysql", "mariadb"]
junit = ["junit-jupiter", "junit-platform"]
testcontainers = ["testcontainers-jupiter", "testcontainers-mysql", "testcontainers-mariadb"]

[plugins]
shadow = "com.gradleup.shadow:8.3.5"
run-paper = "xyz.jpenilla.run-paper:2.3.1"
plugin-yml = "net.minecrell.plugin-yml.bukkit:0.6.0"
flyway = "org.flywaydb.flyway:11.10.3"
jooq = "org.jooq.jooq-codegen-gradle:3.20.5"
